### ISSUE TITLE
Help text on login screen doesn't disappeer after login

### ISSUE THREAD

**Issue by ghost** [BrainCoder/InnovumStripeSystem#4]
The text on the left of the login screen doesn't disappeer after you logged in, we think that this text is kinda useless when you logged in, so maybe it could be replaced with a guild what you can do while logged in

**Comment by ghost** [comment]
<h1>Proposed solution: </h1>
replace in index.html

` <div class="explain"> Please fill in your porsonal number to proceed the striping </div>`

by:

`<div class="explain">`
	`<div class="step step1">`
		`Please fill in your personal number to proceed the striping.`
		`<!-- Or any other text you want to display on the login screen -->`
	`</div>`
	`<div class="step step3">`
		`Please stripe!`
		`<!-- Or any other text you want to display on the logged in screen -->`
	`</div>`
	`<div class="step stepe">`
		`LEARN YOUR STUDENT NUMBER DIPSHIT!`
	`</div>`
`  </div>`

**Comment by legomannetje** [comment]
For the login screen:

Dear member,
Welcome at the Innovum Striping Sytem

Before you can stripe here you need to make
an account at stripes.engineeringeindhoven.nl

When you have done it you can enter your
student number in the input on this screen,
once logged in you can place as many stripes
as your heart desires

Happy striping
The Innovum Board

**Comment by legomannetje** [comment]
For the main screen

Hi {name} or Member,

You are logged in now, in the middle
you can place a stripe, { other features},
and logout. If you need help with
something, please shout "Kut bestuur"
And someone will be on there way in order
to help you!

Happy Striping
The Innovum Board

**Comment by ghost** [comment]
@BrainCoder Can be closed
