### ISSUE TITLE
Magicly apparence of stripes

### ISSUE THREAD

**Issue by ghost** [BrainCoder/InnovumStripeSystem#5]
I keep track of my stripes, and it when up from 2030 to 37706 in about 3 hours. this is about 3 every second, the terminal doesn't allow this maybe button presses. conclusion: something is broken!
@BrainCoder

**Comment by ghost** [comment]
I smell BS

**Comment by ghost** [comment]
This a bug that cost people a lot of money! a positive fall-out isnt a good thing! Why the no fix?

**Comment by BrainCoder** [comment]
Fixed it for you. You now have 50K stripes. Thanks for the positive fallout!
